import { PlaceHolderImages } from './placeholder-images';

export const PlaceHolderProperties = [
    {
      id: 1,
      price: 150000000,
      listing_type: "sale",
      address: "123 Banana Island, Lagos",
      estate_name: "Banana Island",
      city: "Lagos",
      state: "Lagos",
      beds: 4,
      baths: 5,
      sqft: 3500,
      lotSize: 0.25,
      agent: "Apex Realty",
      status: "New",
      home_type: "Duplex",
      is_furnished: true,
      power_supply: "24/7 Generator",
      water_supply: "Borehole",
      security_type: ["Gated Estate", "Security Guards"],
      imageUrl: PlaceHolderImages.find((img) => img.id === "property-1")?.imageUrl ?? "",
      imageHint: PlaceHolderImages.find((img) => img.id === "property-1")?.imageHint ?? "",
    },
    {
      id: 2,
      price: 250000000,
      listing_type: "sale",
      address: "456 Asokoro, Abuja",
      estate_name: "Asokoro",
      city: "Abuja",
      state: "FCT",
      beds: 5,
      baths: 6,
      sqft: 4200,
      lotSize: 0.5,
      agent: "Urban Dwellings",
      status: "Price Reduced",
      home_type: "House",
      is_furnished: true,
      power_supply: "National Grid",
      water_supply: "Water Board",
      security_type: ["Security Guards"],
      imageUrl: PlaceHolderImages.find((img) => img.id === "property-2")?.imageUrl ?? "",
      imageHint: PlaceHolderImages.find((img) => img.id === "property-2")?.imageHint ?? "",
    },
    {
      id: 3,
      price: 8500000,
      price_period: "yearly",
      listing_type: "rent",
      address: "789 GRA, Port Harcourt",
      city: "Port Harcourt",
      state: "Rivers",
      beds: 3,
      baths: 3,
      sqft: 2800,
      lotSize: 0.3,
      agent: "Heartland Homes",
      status: "Coming Soon",
      home_type: "Apartment (Flat)",
      is_furnished: false,
      power_supply: "Generator",
      water_supply: "Borehole",
      security_type: ["Gated Estate"],
      imageUrl: PlaceHolderImages.find((img) => img.id === "property-3")?.imageUrl ?? "",
      imageHint: PlaceHolderImages.find((img) => img.id === "property-3")?.imageHint ?? "",
    },
    {
        id: 4,
        price: 180000000,
        listing_type: "sale",
        address: "101 Maitama, Abuja",
        estate_name: "Maitama",
        city: "Abuja",
        state: "FCT",
        beds: 4,
        baths: 4,
        sqft: 3800,
        lotSize: 0.4,
        agent: "Wayne Enterprises Realty",
        status: "New",
        home_type: "House",
        is_furnished: true,
        power_supply: "24/7 Generator",
        water_supply: "Borehole",
        security_type: ["Security Guards"],
        imageUrl:
          PlaceHolderImages.find((img) => img.id === "property-4")?.imageUrl ?? "",
        imageHint:
          PlaceHolderImages.find((img) => img.id === "property-4")?.imageHint ?? "",
    },
    {
        id: 5,
        price: 320000000,
        listing_type: "sale",
        address: "212 Lekki Phase 1, Lagos",
        estate_name: "Lekki Phase 1",
        city: "Lagos",
        state: "Lagos",
        beds: 6,
        baths: 7,
        sqft: 5500,
        lotSize: 1.2,
        agent: "Queen Consolidated Properties",
        status: "Foreclosure",
        home_type: "Terrace",
        is_furnished: false,
        power_supply: "National Grid",
        water_supply: "Borehole",
        security_type: ["Gated Estate", "Security Guards"],
        imageUrl:
          PlaceHolderImages.find((img) => img.id === "property-5")?.imageUrl ?? "",
        imageHint:
          PlaceHolderImages.find((img) => img.id === "property-5")?.imageHint ?? "",
    },
    {
        id: 6,
        price: 7500000,
        price_period: "yearly",
        listing_type: "rent",
        address: "333 Bodija, Ibadan",
        estate_name: "Bodija",
        city: "Ibadan",
        state: "Oyo",
        beds: 3,
        baths: 4,
        sqft: 2500,
        lotSize: 0.2,
        agent: "STAR Labs Real Estate",
        status: "New",
        home_type: "Apartment (Flat)",
        is_furnished: true,
        power_supply: "Generator",
        water_supply: "Water Board",
        security_type: [],
        imageUrl:
          PlaceHolderImages.find((img) => img.id === "property-6")?.imageUrl ?? "",
        imageHint:
          PlaceHolderImages.find((img) => img.id === "property-6")?.imageHint ?? "",
      },
  ];
