/**
 * This file contains the configuration for the Firebase project.
 *
 * It is used by the Firebase providers to initialize the Firebase app instance.
 *
 * NOTE: This file is auto-generated by the Firebase CLI.
 */
export const firebaseConfig = {
  apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  authDomain: "test-project.firebaseapp.com",
  projectId: "test-project",
  storageBucket: "test-project.appspot.com",
  messagingSenderId: "123456789012",
  appId: "1:123456789012:web:xxxxxxxxxxxxxxxxxxxxxx",
  measurementId: "G-XXXXXXXXXX"
};
