
/**
 * This file contains the configuration for the Firebase project.
 *
 * It is used by the Firebase providers to initialize the Firebase app instance.
 *
 * NOTE: This file is auto-generated by the Firebase CLI.
 */
export const firebaseConfig = {
  "projectId": "studio-109074013-9a431",
  "appId": "1:1022383304197:web:420213a3114583da62766c",
  "apiKey": "AIzaSyCKiZss9W1miv7A5H-RswP_PRpykA6RBCk",
  "authDomain": "studio-109074013-9a431.firebaseapp.com",
  "messagingSenderId": "1022383304197"
};
