/**
 * This file contains the configuration for the Firebase project.
 *
 * It is used by the Firebase providers to initialize the Firebase app instance.
 *
 * NOTE: This file is auto-generated by the Firebase CLI.
 */
export const firebaseConfig = {
  apiKey: "AIzaSyB-LwTVi9e4n7aV3h9o6a_2Z8hZRL9m_aM",
  authDomain: "dev-project-33751.firebaseapp.com",
  projectId: "dev-project-33751",
  storageBucket: "dev-project-33751.appspot.com",
  messagingSenderId: "1056588237255",
  appId: "1:1056588237255:web:d27376fb89a5448b11116a",
  measurementId: "G-K5M9E77PC3"
};
